package com.russel.atm.simulator.common;

import java.io.Serializable;

/**
 * @author Rassul Hessampour
 * @version $Revision: 1.1.0 $
 */
public abstract class BaseService implements ServiceAttributeAware, Serializable {

    private static final long serialVersionUID = 613025303647443202L;

    /** The request uuid. */
    private String requestUUID;//can also be generated by the client
    
    /* (non-Javadoc)
     * @see com.russel.atm.simulator.common.Service#getRequestUUID()
     */
    public String getRequestUUID() {
        return requestUUID;
    }

    /* (non-Javadoc)
     * @see com.russel.atm.simulator.common.BaseService#setRequestUUID(java.lang.String)
     */
    public void setRequestUUID(String UUID) {
        this.requestUUID = UUID;
    }

    /* (non-Javadoc)
     * @see com.russel.atm.simulator.common.ServiceAttributeAware#getServiceAttribute()
     */
    public ServiceAttribute getServiceAttribute() {
        throw new UnsupportedOperationException();
    }
}