package com.russel.atm.simulator.iso;

/**
 * @author Rassul Hessampour
 * @version $Revision: 1.1.0 $
 */
public enum ISOField {

    PRIMARY_BIT_MAP(-1),
    MTI(0),
    //    PRIMARY_BIT_MAP(1),
    SECONDARY_BIT_MAP(1),
    PAN(2),
    PROCESSING_CODE(3),
    TRANSACTION_AMOUNT(4),
    TRANSACTION_FEE_AMOUNT(6),
    TRANSMISSON_DATE_TIME(7),
    SYSTEM_TRACE_AUDIT_NUMBER(11),
    LOCAL_TRANSACTION_DATE_TIME(12),
    EXPIRY_DATE(14),
    SETTLEMENT_DATE(15),
    CAPTURE_DATE(17),
    MERCHANT_TYPE(18),
    ACQUIRE_COUNTRY_CODE(19),
    POINT_OF_SERVICE_DATA_CODE(22),
    FUNCTION_CODE(24),
    REVERSAL_REASON_CODE(25),
    CARD_ACCEPTOR_BUSINESS_CODE(26),
    ORIGINAL_AMOUNT(30),
    ACQUIRER_INSTITUTION_ID(32),
    FORWARDING_INSTITUTION_ID(33),
    TRACK_2_DATA(35),
    RETRIEVAL_REFERENCE_NO(37),
    AUTHORIZATION_ID_RESPONSE(38),
    ACTION_CODE(39),
    CARD_ACCEPT_TERMINAL_ID(41),
    CARD_ACCEPT_ID_CODE(42),
    CARD_ACCEPT_NAME_LOCATION(43),
    ADDITIONAL_RESPONSE_DATA(44),
    FEES_AMOUNT(46),
    ADDITIONAL_PRIVATE_DATA(48),
    TRANSACTION_CURRENCY_CODE(49),
    SETTLEMENT_CURRENCY_CODE(50),
    PIN_DATA(52),
    SECURITY_RELATED_CONTROL_INFORMATION(53),
    ADDITIONAL_AMOUNTS(54),
    ORIGINAL_DATA_ELEMENTS(56),
    NETWORK_MANAGEMENT_INFORMATION_CODE(70),
    DATA_RECORD(72),
    NUMBER_CREDITS(74),
    REVERSAL_NUMBER_CREDITS(75),
    NUMBER_DEBITS(76),
    REVERSAL_NUMBER_DEBITS(77),
    NUMBER_TRANSFER(78),
    REVERSAL_NUMBER_TRANSFER(79),
    NUMBER_INQUIRIES(80),
    NUMBER_AUTHORIZATIONS(81),
    AMOUNT_CREDITS(86),
    REVERSAL_AMOUNT_CREDITS(87),
    AMOUNT_DEBITS(88),
    REVERSAL_AMOUNT_DEBITS(89),
    TRANSACTION_DESTINATION_INSTITUTION_ID(93),
    TRANSACTION_ORIGINATOR_INSTITUTION_ID(94),
    REPLACEMENT_AMOUNT(95),
    KEY_MANAGEMENT_DATA(96),
    NET_SETTLEMENT_AMOUNT(97),
    /**
     * Added in Dynamic Password Generator from pooya
     */
    ACQUIRE_INSTITUTE_CODE(100),
    CARD_NUM_LIST(101),
    ACCOUNT_NO_1(102),
    ACCOUNT_NO_2(103),
    CUSTOMER_NO(104),
    DEFAULT_DESTINATION_ACCOUNT_NO(105),
    INTERNATIONAL_ACCOUNT_VERIFICATION_DATA(111),
    ADDITIONAL_RESPONSE_DATA2(115),
    PHONE_ACCESS_PARAMETER(116),
    MOBILE_ACCESS_PARAMETER(117),
    IP_ACCESS_PARAMETER(118),
    PRIVATE_USED(124),
    MAC_CODE(128);

    private int position;

    ISOField(int position) {
        this.position = position;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

}