package com.russel.atm.simulator.iso;

/**
 * @author Rassul Hessampour
 * @version $Revision: 1.1.0 $
 */
public enum ResponseCode {

    APPROVED("000"),
    APPROVED_WITH_ID("001"),
    APPROVED_VIP("003"),
    APPROVED_UPDATE_CHIP("007"),
    REJECTED("100"),
    EXPIRED_CARD("101"),
    SUSPECTED_FRAUD("102"),
    PRIVATE_CARD("104"),
    ALLOWABLE_NUMBER_ON_PIN_ENTRY_TRIES_EXCEEDED("106"),
    REFER_TO_CARD_ISSUER("107"),
    REFER_TO_CARD_ISSUER_SPECIAL_CONDITION("108"),
    BAD_MERCHANT("109"),
    INVALID_AMOUNT("110"),
    INVALID_CARD_NUMBER("111"),
    PIN_ELEMENT_REQUIRED_FOR_THIS_TRANSACTION_TYPE("112"),
    UNKNOWN_CARD("114"),
    FUNCTION_NOT_AVAILABLE("115"),
    NO_SUFFICIENT_FUNDS("116"),
    INCORRECT_PIN("117"),
    NO_SUCH_CARD("118"),
    CARD_HOLDER_TRANSACTION_NOT_PERMITTED("119"),
    TERMINAL_TRANSACTION_NOT_PERMITTED("120"),
    EXCEEDS_WITHDRAWAL_FREQUENCY_LIMIT("121"),
    SECURITY_VIOLATION("122"),
    WITHDRAWAL_FREQUENCY_EXCEEDED("123"),
    CARD_NOT_IN_SERVICE("125"),
    WRONG_PIN_FORMAT("126"),
    ERROR_PIN_LENGTH("127"),
    CRYPTOGRAPHIC_ERROR("128"),
    //    SUSPECTED_FRAUD("129", StringUtil.EMPTY),
    DUPLICATE_BILL_PAYMENT_EXIST("131"),
    INVALID_BILLER_ID("132"),//@TODO : Rename in base of shetab or pooya definition
    NO_CREDIT_ACCOUNT_2("135"),
    NO_CREDIT_ACCOUNT("180"),
    NO_CHEQUE_ACCOUNT("181"),
    NO_SAVING_ACCOUNT("182"),
    BAD_CVV("183"),
    INVALID_DATE("184"),
    FUNCTION_NOT_AVAILABLE_TO_USER("185"), //@TODO : Rename in base of shetab or pooya definition
    REJECTED_PICK_UP_CARD("200"),
    EXPIRED_CARD_PICK_UP_CARD("201"),
    FRAUD_SUSPECTED_PICK_UP_CARD("202"),
    RESERVED_USAGE_PICK_UP_CARD("204"),
    ISSUER_CALL_FOR_ACQUIRER_SECURITY_SERVICE_PICK_UP_CARD("205"),
    NUMBER_OF_PIN_VALIDATION_ATTEMPTS_EXCEEDED("206"),
    SPECIAL_CONDITION_PICK_UP_CARD("207"),
    CARD_LOST_PICK_UP_CARD("208"),
    CARD_STOLEN_PICK_UP_CARD("209"),
    FRAUD_SUSPECTED_PICK_UP("210"),
    ALTERNATIVE_AMOUNT_REVERSED("280"),
    CARD_PICK_UP("299"),
    SUCCESSFULLY_PROCESSED("300"),
    NOT_SUPPORTED_BY_RECEIVER("301"),
    UNABLE_TO_FIND_RECORD_IN_THE_FILE("302"),
    DUPLICATE_RECORD_OLD_RECORD_REPLACED("303"),
    ZONE_CONTROL_ERROR("304"),
    FILE_LOCKED("305"),
    UNSUCCESSFUL("306"),
    FORMAT_ERROR("307"),
    FILE_UNKNOWN("309"),
    BALANCE_RECORD_CLEARED("382"),
    BALANCE_REQUEST("383"),
    REVERSAL_ACCEPTED("400"),
//    REVERSAL_ACCEPTED("480", StringUtil.EMPTY),
    INVALID_REVERSAL_AMOUNT("481"),
    COUNTERS_NOT_AVAILABLE("503"),
    RECONCILIATION_DONE("581"),
    RECONCILIATION_PROCESS_NOT_AVAILABLE("582"),
    CUT_OFF_IN_PROGRESS("800"),
    CONNECTION_NOT_ACCEPTED("880"),
    INVALID_TRANSACTION("902"),
    CARD_ISSUER_OR_SWITCH_INOPERATIVE("907"),
    TRANSACTION_RECEIVER_NOT_REFERENCED_FOR_SWITCH("908"),
    SYSTEM_DEFECT("909"),
    TIMEOUT("911"),
    CARD_ISSUER_NOT_AVAILABLE("912"),
    DUPLICATE_RECORD_NEW_RECORD_REJECTED("913"),
    RECORD_NOT_FOUND("914"),
    ISSUER_NOT_FOUND("992"),
    PIN_VERIFICATION_ERROR("993"),
    TRANSACTION_PROCESSING_ERROR("994"),
    SERVER_PROCESSING_ERROR("995");

    private String code;

    ResponseCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }


}
